### ISSUE TITLE
A BUG in "About Maid Fiddler"

### ISSUE THREAD

**Issue by TheCGDF** [denikson/CM3D2.MaidFiddler#27] opened 2017-07-12 06:13 UTC
Hello, I want to report two BUG in "about maid fiddler" .
I found the first bug when I wanted to visit your github from the link in "about maid fiddler". When Player open the "about maid fiddler" and then switch to any other windows (such as Chrome). The "about maid fiddler" will disapper .At the same time, the "maid fiddler" and "cm3d2" will be locked. Player can do nothing except closing the game without saving. 
Antoher bug is , when player switch to "traits and fetishe",maid fiddler will enter a  infinite loop(load-refresh-load-refresh...).My CM3D2's version is 1.51.
In fact I noticed that the maid fiddler hasn't updated for a long time. So I thought you may be not intreseted in fixing them. But I still want to report because maybe someone will join the project and fix it.
And, really  appreciate your works!

**Comment by ghorsington** [comment] 2017-07-12 07:16
Greetings!

Thank you for the information. Let me address the issues separately:

### About Maid Fiddler dialog

The dialogs in Maid Fiddler are made with ShowInTaskbar property set to `false`, which in turn makes them inaccessible from taskbar if you change the window (whoops). I'll fix that, but if you are impatient you can do one of the following:

1. Use Alt+Tab. Even if the dialog is "hidden" from taskbar, you can still access (and close it) using Alt+Tab to switch between windows. No need to close the whole game.
2. Fix it in the source code and recompile. It is just as easy as going through the `*.Designer.cs` files, finding the `ShowInTaskbar` property and setting it to `true`.

### The loop in Traits and Fetishes tab

Could you elaborate on that a bit? Maid Fiddler doesn't run any code when the user changes tabs in the GUI, so nothing special should happen. Moreover, running the Debug build doesn't seem to show any infinite maid updating loops when viewing or editing traits and fetishes.
Perhaps you could provide more information about this? For instance, what did you exactly try to do, can the issue be replicated (and how)? Maybe a list of installed DLC could help as well (you can get a list of them through Maid Fiddler's About dialog).

**Comment by TheCGDF** [comment] 2017-07-12 13:44
I tested the "Traits and Fetishes" more times just know so that I can get a more detailed description. If I switch to "traits and fetishes" and do nothing, it will loops forever (refresh traits list-not responding-refresh traits list-not responding-refresh traits list...).And I found something intreseting when I was writing these words. If I switch to other windows and then switch back. The loop will stop. By the way, I am curious about whether it is normal that the GUI always loads slowly.
I recorded a video about it and uploaded it . You can download and check it.
[fm.zip](https://github.com/denikson/CM3D2.MaidFiddler/files/1142147/fm.zip)

**Comment by TheCGDF** [comment] 2017-07-12 13:47
In addition, I found some traits are not translated.
![tim 20170712214550](https://user-images.githubusercontent.com/17256673/28120752-8e39cec8-674b-11e7-86a5-7477a073067b.png)
Maybe there are interrelated?

**Comment by TheCGDF** [comment] 2017-07-12 14:09
Something else...I updated the Chinese translation by the "Get Official translations" button. And I found it is strange that there are some gibberish in it.
![tim 20170712215910](https://user-images.githubusercontent.com/17256673/28121486-d83547e4-674d-11e7-9c85-0c358d682224.png)
And I checked the raw translation file in thisrepository, there are no gibberish in it. Then I download it from github by myself. There are no gibberish in it, too.Maybe something works wrong when downloading?

**Comment by ghorsington** [comment] 2017-07-12 14:49
Thank you for all this information! 
Well, never seen that one before.

---

**Premature TL;DR:** 1) Problem is in Mono's implementation of WinForms. Can't do anything about it without rewriting the whole GUI (which I am already doing). 2) The official translation hasn't been updated for a long time (I don't really play the game that often). 3) You found yet another bug, thank you.

---

### The lagging issue

I would assume one (or some kind combination) of the following:

1. The computer is slow, which causes WinForms to be **very** slow to render. After all, this version of Maid Fidder uses Mono's WinForms, which in turn is implemented using System.Drawing instead of direct native implementation.
2. You do use NTLEA to emulate the locale? Some other locale emulators might cause weird slowdowns.
3. Some other part of the computer's setup might be causing problems with WinForms.

I must admit that WinForms wasn't the best choice for the GUI -- some users have even reported that the GUI fails to launch on their computers altogether (for instance #23) . It was, however, the only one included with CM3D2's Mono distribution, which made developing a bit easier..

As of right now, I suggest to try and tamper with process priority of CM3D2 and try other locale emulators, for instance. This "lag" issue most likely won't be fixed in the beta builds (which is, again, due to WinForms). I am working on rewriting Maid Fiddler to use a separate program as a GUI, so that might be the only solution. Unfortunately, I still am quite busy with my studies, so the progress is slow (not that it's totally ceased -- I have been pushing changes to [a separate branch](https://github.com/denikson/CM3D2.MaidFiddler/tree/wpf)).

**IF** you do want to make sure that the problem is really not in Maid Fiddler, you can use this Debug version of the plugin:
[MF_Plugin_Debug.zip](https://github.com/denikson/CM3D2.MaidFiddler/files/1142293/MF_Plugin_Debug.zip)
This one will output all debug info of Maid Fiddler into the console while CM3D2 runs. If there is an infinite loop that is caused by Maid Fiddler, you will see the same debug messages looping infinitely. Otherwise, the console should be rather normal.

### The age of translations

The translations are indeed very old. If you do want to translate them, you can do so manually with a translation file found in Maid Fiddler's Config folder (which in turn is in the UnityInjector folder).

As a heads-up, the Chinese translation is really old too. You're better off finding a more recent version (assuming there is such).

### The weird characters

Darn. And I thought I had done it correctly on the first try.

It seems like another issue (this time a fixable one): Maid Fiddler downloads the translation from GitHub in smaller, about 1 KB chunks and converts them to Unicode. It seems I forgot to take into account that Unicode characters' size varies from 1 to 4 bytes, which in turn causes these weird characters. Fortunately, that is simple to fix.

**Closed as completed** 2017-07-12 15:42 UTC
Labels: bug, minor

**Comment by TheCGDF** [comment] 2017-07-12 16:15
【1】My computer is Surface Pro 4 (i7 6650U+16GB RAM+512GB SSD). It doesn't have graphics card. Maybe that's the reason. Surface Pro is not designed to play games.
【2】I was using a encapsulated CM3D2x64.exe. I tried NTLEA instsead of it and then got a interesting result. The infinite loop never appeared again. And the render time was cut by half . That's a acceptable result although I don't know what happpened.
【3】I'm not eager for translation , so don't worry. I can read english and japanese so the translation is not essential to me. I used the translation just because I was really curious to know how official translates the intreseting yotogi skills because my textbooks will nerver teach me these words. XD

**Comment by ghorsington** [comment] 2017-07-12 16:24
A Surface Pro should handle Unity Engine games quite well.

So it was the locale after all. Different locale emulation methods perform very differently, so most of the time if there is a rendering problem (or a problem at all), one should attempt to try a different emulator first. For CM3D2, NTLEA seems to work quite well. All this notwithstanding, it's good to hear the problem is now resolved.

P.S. I take no liability for Chinese/Japanese translations, since they're just moontalk to me. I do know, however, that the Chinese translation was done by a native, so it should be quite accurate.
